-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#1a1110",
  base01 = "#140c0b",
  base02 = "#231918",
  base03 = "#534341",
  base04 = "#d8c2be",
  base05 = "#f1dedc",
  base06 = "#392e2c",
  base07 = "#423735",

  base08 = "#d9b978",
  base09 = "#dfc38c",
  base0A = "#e7bdb7",
  base0B = "#ffb4a9",
  base0C = "#574419",
  base0D = "#73342c",
  base0E = "#5d3f3b",
  base0F = "#da9a91",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#73342c',
  fg = '#ffdad5', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#cea450',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#a08c89',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#dfc38c',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e7bdb7',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#904a41',
})